version: '3.9'

services:
  cyberok:
    build: .
    command: ./wait-for-postgres.sh db "./cyberok"
    ports:
      - "${HTTP_EXTERNAL_PORT}:8000"
    depends_on:
      - db
      #      - migrate
      - pgadmin
    environment:
      DB_PASSWORD: root

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cyberok_db
    ports:
      - "${DB_EXTERNAL_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "${PG_ADMIN_PORT}:80"




